AWSTemplateFormatVersion: "2010-09-09"
Description: "OIDCAccessProxy"
Resources:
  OIDCAccessProxyRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      RoleName: OIDCAccessProxy-Role
  OIDCAccessProxyInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    DependsOn: OIDCAccessProxyRole
    Properties:
      InstanceProfileName: "OIDCAccessProxy-instance-profile"
      Roles:
        -
          Ref: OIDCAccessProxyRole
  OIDCAccessProxyCodePipelineAccess:
    Type: "AWS::IAM::Policy"
    DependsOn: OIDCAccessProxyRole
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - "s3:GetBucketAcl"
              - "s3:GetBucketCORS"
              - "s3:GetBucketLocation"
              - "s3:GetBucketLogging"
              - "s3:GetBucketNotification"
              - "s3:GetBucketPolicy"
              - "s3:GetBucketRequestPayment"
              - "s3:GetBucketTagging"
              - "s3:GetBucketVersioning"
              - "s3:GetBucketWebsite"
              - "s3:GetLifecycleConfiguration"
              - "s3:GetObject"
              - "s3:GetObjectAcl"
              - "s3:GetObjectTagging"
              - "s3:GetObjectTorrent"
              - "s3:GetObjectVersion"
              - "s3:GetObjectVersionAcl"
              - "s3:GetObjectVersionTagging"
              - "s3:GetObjectVersionTorrent"
              - "s3:GetReplicationConfiguration"
              - "s3:ListAllMyBuckets"
              - "s3:ListBucket"
              - "s3:ListBucketMultipartUploads"
              - "s3:ListBucketVersions"
              - "s3:ListMultipartUploadParts"
            Resource: "arn:aws:s3:::codepipeline*"
      PolicyName: OIDCAccessProxy-read-codepipeline
      Roles:
        -
          Ref: OIDCAccessProxyRole
  OIDCAccessProxyECRLogin:
    Type: "AWS::IAM::Policy"
    DependsOn: OIDCAccessProxyRole
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - "ecr:GetAuthorizationToken"
            Resource: "*"
      PolicyName: OIDCAccessProxy-ecr-login
      Roles:
        -
          Ref: OIDCAccessProxyRole
  OIDCAccessProxySQSSend:
    Type: "AWS::IAM::Policy"
    DependsOn: OIDCAccessProxyRole
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - "sqs:ChangeMessageVisibility"
              - "sqs:ChangeMessageVisibilityBatch"
              - "sqs:CreateQueue"
              - "sqs:GetQueueAttributes"
              - "sqs:GetQueueUrl"
              - "sqs:ListDeadLetterSourceQueues"
              - "sqs:ListQueues"
              - "sqs:PurgeQueue"
              - "sqs:ReceiveMessage"
              - "sqs:SendMessage"
              - "sqs:SendMessageBatch"
              - "sqs:SetQueueAttributes"
            Resource: "arn:aws:sqs:us-west-2:*:OIDCAccessProxy-fluentd-sqs"
      PolicyName: OIDCAccessProxy-sqs-send
      Roles:
        -
          Ref: OIDCAccessProxyRole
  OIDCAccessProxyCredstashRead:
    Type: "AWS::IAM::Policy"
    DependsOn: OIDCAccessProxyRole
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - "dynamodb:GetItem"
              - "dynamodb:Query"
              - "dynamodb:Scan"
            Resource: "arn:aws:dynamodb:*:*:table/credential-store"
      PolicyName: OIDCAccessProxy-credstash
      Roles:
        -
          Ref: OIDCAccessProxyRole
  OIDCAccessProxyTagAccess:
    Type: "AWS::IAM::Policy"
    DependsOn: OIDCAccessProxyRole
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - "ec2:DescribeTags"
            Resource: "*"
      PolicyName: OIDCAccessProxy-describe-tags
      Roles:
        -
          Ref: OIDCAccessProxyRole
  OIDCAccessProxyCodeDeploy:
    Type: "AWS::IAM::Policy"
    DependsOn: OIDCAccessProxyRole
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - "codedeploy:*"
            Resource: "arn:aws:codedeploy:*:*:application:OIDCAccessProxy-*"
      PolicyName: OIDCAccessProxy-code-deploy
      Roles:
        -
          Ref: OIDCAccessProxyRole
